/**
 * Fine-grained permissions + RBAC matrix.
 * Org-scoped checks: constants/org-roles.ts
 * Demand-side: **client** (advertisers.* kept as deprecated aliases).
 */

import { normalizeRole, type Role } from "@/constants/roles";

export const PERMISSIONS = [
  // Identity / auth
  "auth.session.read",
  "auth.session.write",
  "auth.mfa.manage",
  "auth.devices.manage",
  // Users / orgs
  "users.profile.read",
  "users.profile.write",
  "users.admin.read",
  "users.admin.write",
  "organizations.read",
  "organizations.write",
  "organizations.billing",
  "organizations.audit.read",
  "organizations.api_keys.manage",
  "teams.read",
  "teams.write",
  // Supply / demand
  "workers.profile.read",
  "workers.profile.write",
  "clients.profile.read",
  "clients.profile.write",
  /** @deprecated Use clients.profile.read */
  "advertisers.profile.read",
  /** @deprecated Use clients.profile.write */
  "advertisers.profile.write",
  // Work graph
  "campaigns.read",
  "campaigns.create",
  "campaigns.update",
  "campaigns.publish",
  "campaigns.archive",
  "tasks.read",
  "tasks.create",
  "marketplace.browse",
  "marketplace.claim",
  "applications.submit",
  "applications.review",
  "assignments.read",
  "assignments.manage",
  "submissions.create",
  "submissions.review",
  "verification.run",
  // Money
  "wallet.read",
  "wallet.credit",
  "wallet.debit",
  "payments.create",
  "payments.refund",
  "escrow.hold",
  "escrow.release",
  "withdrawals.request",
  "withdrawals.approve",
  "rewards.grant",
  "referrals.manage",
  // Comms
  "notifications.read",
  "notifications.send",
  "messaging.read",
  "messaging.send",
  // AI / specialized work verticals
  "ai_jobs.read",
  "ai_jobs.manage",
  "ai_datasets.read",
  "ai_datasets.manage",
  "ai_labeling.work",
  "ai_labeling.review",
  // Trust
  "moderation.act",
  "reports.create",
  "reports.review",
  "trust.review",
  "kyc.submit",
  "kyc.review",
  "disputes.open",
  "disputes.resolve",
  // Platform
  "admin.access",
  "analytics.read",
  "analytics.admin",
  "api.keys.manage",
  "developer.portal",
  "docs.read",
  "support.ticket",
  "support.agent",
  "settings.read",
  "settings.write",
  "feature_flags.manage",
  // Operations console
  "ops.command_center.read",
  "ops.views.read",
  "ops.commands.execute",
  "ops.queues.manage",
  "ops.audit.read",
  "ops.health.read",
  "ops.playbooks.read",
  "ops.finance.act",
  "ops.moderation.act",
  // AI plugin platform
  "ai.plugins.read",
  "ai.plugins.execute",
  "ai.recommendations.read",
  "ai.decisions.write",
  "ai.config.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const CLIENT_PERMISSIONS = [
  "auth.session.read",
  "auth.session.write",
  "auth.mfa.manage",
  "auth.devices.manage",
  "users.profile.read",
  "users.profile.write",
  "clients.profile.read",
  "clients.profile.write",
  "advertisers.profile.read",
  "advertisers.profile.write",
  "organizations.read",
  "organizations.write",
  "organizations.billing",
  "organizations.audit.read",
  "organizations.api_keys.manage",
  "teams.read",
  "teams.write",
  "campaigns.read",
  "campaigns.create",
  "campaigns.update",
  "campaigns.publish",
  "campaigns.archive",
  "tasks.read",
  "tasks.create",
  "applications.review",
  "assignments.read",
  "assignments.manage",
  "submissions.review",
  "wallet.read",
  "payments.create",
  "escrow.hold",
  "notifications.read",
  "messaging.read",
  "messaging.send",
  "ai_jobs.read",
  "ai_jobs.manage",
  "ai_datasets.read",
  "ai_datasets.manage",
  "ai_labeling.review",
  "reports.create",
  "disputes.open",
  "analytics.read",
  "docs.read",
  "support.ticket",
  "settings.read",
  "settings.write",
] as const satisfies readonly Permission[];

/**
 * Default grant matrix. Org-scoped checks still apply via org-roles.
 * `*` means all permissions (super_admin only).
 */
export const ROLE_PERMISSIONS: Record<Role, readonly Permission[] | "*"> = {
  guest: ["marketplace.browse", "docs.read"],
  worker: [
    "auth.session.read",
    "auth.session.write",
    "auth.mfa.manage",
    "auth.devices.manage",
    "users.profile.read",
    "users.profile.write",
    "workers.profile.read",
    "workers.profile.write",
    "marketplace.browse",
    "marketplace.claim",
    "applications.submit",
    "assignments.read",
    "tasks.read",
    "submissions.create",
    "wallet.read",
    "withdrawals.request",
    "notifications.read",
    "messaging.read",
    "messaging.send",
    "ai_labeling.work",
    "reports.create",
    "kyc.submit",
    "disputes.open",
    "docs.read",
    "support.ticket",
    "settings.read",
    "settings.write",
  ],
  client: CLIENT_PERMISSIONS,
  /** @deprecated Alias of client */
  advertiser: CLIENT_PERMISSIONS,
  org_member: [
    "auth.session.read",
    "organizations.read",
    "teams.read",
    "campaigns.read",
    "tasks.read",
    "analytics.read",
    "settings.read",
  ],
  org_admin: [
    "auth.session.read",
    "organizations.read",
    "organizations.write",
    "organizations.billing",
    "organizations.audit.read",
    "organizations.api_keys.manage",
    "teams.read",
    "teams.write",
    "campaigns.read",
    "campaigns.create",
    "campaigns.update",
    "campaigns.publish",
    "campaigns.archive",
    "tasks.read",
    "tasks.create",
    "applications.review",
    "assignments.manage",
    "submissions.review",
    "wallet.read",
    "payments.create",
    "escrow.hold",
    "analytics.read",
    "settings.read",
    "settings.write",
  ],
  moderator: [
    "auth.session.read",
    "moderation.act",
    "reports.review",
    "trust.review",
    "submissions.review",
    "verification.run",
    "disputes.open",
    "ops.command_center.read",
    "ops.views.read",
    "ops.queues.manage",
    "ops.moderation.act",
    "ops.playbooks.read",
  ],
  support: [
    "auth.session.read",
    "users.admin.read",
    "support.ticket",
    "support.agent",
    "reports.review",
    "disputes.open",
    "ops.command_center.read",
    "ops.views.read",
    "ops.audit.read",
    "ops.playbooks.read",
  ],
  reviewer: [
    "auth.session.read",
    "submissions.review",
    "verification.run",
    "ops.command_center.read",
    "ops.views.read",
    "ops.queues.manage",
    "ops.playbooks.read",
    "ai.plugins.read",
    "ai.plugins.execute",
    "ai.recommendations.read",
    "ai.decisions.write",
  ],
  operations: [
    "auth.session.read",
    "campaigns.read",
    "campaigns.archive",
    "assignments.manage",
    "submissions.review",
    "notifications.send",
    "ops.command_center.read",
    "ops.views.read",
    "ops.commands.execute",
    "ops.queues.manage",
    "ops.audit.read",
    "ops.health.read",
    "ops.playbooks.read",
    "ai.plugins.read",
    "ai.plugins.execute",
    "ai.recommendations.read",
  ],
  finance: [
    "auth.session.read",
    "wallet.read",
    "wallet.credit",
    "wallet.debit",
    "payments.create",
    "payments.refund",
    "escrow.release",
    "withdrawals.approve",
    "ops.command_center.read",
    "ops.views.read",
    "ops.commands.execute",
    "ops.queues.manage",
    "ops.audit.read",
    "ops.health.read",
    "ops.finance.act",
    "ops.playbooks.read",
  ],
  auditor: [
    "auth.session.read",
    "organizations.audit.read",
    "analytics.read",
    "ops.command_center.read",
    "ops.views.read",
    "ops.audit.read",
    "ops.health.read",
    "ops.playbooks.read",
  ],
  admin: [
    "auth.session.read",
    "users.admin.read",
    "users.admin.write",
    "organizations.read",
    "organizations.write",
    "organizations.audit.read",
    "campaigns.read",
    "campaigns.archive",
    "submissions.review",
    "verification.run",
    "wallet.credit",
    "wallet.debit",
    "payments.refund",
    "escrow.release",
    "withdrawals.approve",
    "rewards.grant",
    "referrals.manage",
    "notifications.send",
    "moderation.act",
    "reports.review",
    "trust.review",
    "kyc.review",
    "disputes.resolve",
    "admin.access",
    "analytics.admin",
    "feature_flags.manage",
    "settings.write",
    "ops.command_center.read",
    "ops.views.read",
    "ops.commands.execute",
    "ops.queues.manage",
    "ops.audit.read",
    "ops.health.read",
    "ops.playbooks.read",
    "ops.finance.act",
    "ops.moderation.act",
    "ai.plugins.read",
    "ai.plugins.execute",
    "ai.recommendations.read",
    "ai.decisions.write",
    "ai.config.manage",
  ],
  super_admin: "*",
  developer: [
    "auth.session.read",
    "api.keys.manage",
    "developer.portal",
    "docs.read",
    "analytics.read",
    "organizations.api_keys.manage",
    "ops.health.read",
    "ai.plugins.read",
  ],
  api_client: [
    "campaigns.read",
    "tasks.read",
    "tasks.create",
    "marketplace.browse",
    "submissions.create",
    "submissions.review",
    "wallet.read",
    "payments.create",
    "api.keys.manage",
  ],
};

export function roleHasPermission(role: Role, permission: Permission): boolean {
  const normalized = normalizeRole(role);
  const grants = ROLE_PERMISSIONS[normalized];
  if (grants === "*") return true;
  return grants.includes(permission);
}

export function rolesHavePermission(
  roles: readonly Role[],
  permission: Permission,
): boolean {
  return roles.some((role) => roleHasPermission(role, permission));
}
