/**
 * @module features/notifications/constants
 */
export {
  CHANNEL_ADAPTER_KEYS,
  CHANNEL_CAPABILITIES,
  DELIVERY_POLICY_MODES,
  DIGEST_FREQUENCIES,
  HUB_EVENT_TO_DOMAIN,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_HUB_EVENTS,
  NOTIFICATION_INTENT_STATUSES,
  NOTIFICATION_JOB_STATUSES,
  NOTIFICATION_PRIORITIES,
  PREFERENCE_SCOPES,
  RECIPIENT_ROLES,
} from "@/constants/notification";
