/**
 * Starter connector manifests — Public API + Webhook contracts only.
 */

import type { ConnectorManifest } from "@/lib/marketplace/types";

export const STARTER_CONNECTORS: ConnectorManifest[] = [
  {
    id: "generic.webhook",
    name: "Generic Webhook",
    description: "Forward ZOLANZO events to any HTTPS endpoint via the Webhook Platform.",
    category: "communication",
    version: "1.0.0",
    requiredScopes: ["webhooks.read", "webhooks.write"],
    supportedWebhooks: [
      "assignment.completed",
      "campaign.completed",
      "payment.completed",
      "trust.updated",
      "report.generated",
    ],
    supportedApiEndpoints: ["/api/v1/webhooks"],
    configurationSchema: [
      {
        key: "endpointUrl",
        label: "Endpoint URL",
        type: "url",
        required: true,
      },
      {
        key: "eventTypes",
        label: "Event types (comma-separated)",
        type: "string",
        required: true,
        defaultValue: "assignment.completed",
      },
    ],
    healthChecks: ["endpoint_reachable", "secret_present"],
    oauthCapable: false,
    apiKeyCapable: false,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Notify Slack channels when campaigns, payments, or trust events occur.",
    category: "communication",
    version: "1.0.0",
    requiredScopes: [
      "webhooks.read",
      "webhooks.write",
      "campaigns.read",
      "payments.read",
      "trust.read",
    ],
    supportedWebhooks: [
      "campaign.completed",
      "payment.completed",
      "trust.updated",
      "assignment.completed",
    ],
    supportedApiEndpoints: [
      "/api/v1/campaigns",
      "/api/v1/payments/{id}",
      "/api/v1/trust/profiles/{subjectId}",
    ],
    configurationSchema: [
      {
        key: "channel",
        label: "Default channel",
        type: "string",
        required: true,
        defaultValue: "#zolanzo",
      },
      {
        key: "notifyOnTrustDecline",
        label: "Notify on trust decline",
        type: "boolean",
        defaultValue: true,
      },
    ],
    healthChecks: ["oauth_token", "channel_access"],
    oauthCapable: true,
    apiKeyCapable: false,
  },
  {
    id: "microsoft.teams",
    name: "Microsoft Teams",
    description: "Post operational updates to Teams channels via webhooks + Public API.",
    category: "communication",
    version: "1.0.0",
    requiredScopes: ["webhooks.read", "webhooks.write", "reports.read"],
    supportedWebhooks: [
      "report.generated",
      "campaign.completed",
      "automation.execution.completed",
    ],
    supportedApiEndpoints: ["/api/v1/reports", "/api/v1/campaigns"],
    configurationSchema: [
      {
        key: "teamId",
        label: "Team ID",
        type: "string",
        required: true,
      },
      {
        key: "channelId",
        label: "Channel ID",
        type: "string",
        required: true,
      },
    ],
    healthChecks: ["oauth_token", "channel_access"],
    oauthCapable: true,
    apiKeyCapable: false,
  },
  {
    id: "google.workspace",
    name: "Google Workspace",
    description: "Export weekly executive reports to Drive and calendar reminders.",
    category: "productivity",
    version: "1.0.0",
    requiredScopes: ["reports.read", "reports.generate", "forecast.read"],
    supportedWebhooks: ["report.generated", "forecast.generated"],
    supportedApiEndpoints: [
      "/api/v1/reports",
      "/api/v1/reports/generate",
      "/api/v1/forecasts",
    ],
    configurationSchema: [
      {
        key: "driveFolderId",
        label: "Drive folder ID",
        type: "string",
        required: true,
      },
      {
        key: "calendarId",
        label: "Calendar ID",
        type: "string",
        required: false,
      },
    ],
    healthChecks: ["oauth_token", "drive_access"],
    oauthCapable: true,
    apiKeyCapable: false,
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "Connect ZOLANZO to Zapier using Public API keys and signed webhooks.",
    category: "automation",
    version: "1.0.0",
    requiredScopes: ["webhooks.read", "webhooks.write", "campaigns.read"],
    supportedWebhooks: [
      "assignment.claimed",
      "assignment.completed",
      "campaign.created",
      "payment.completed",
    ],
    supportedApiEndpoints: ["/api/v1/campaigns", "/api/v1/assignments", "/api/v1/webhooks"],
    configurationSchema: [
      {
        key: "zapHookUrl",
        label: "Zap catch hook URL",
        type: "url",
        required: true,
      },
    ],
    healthChecks: ["hook_reachable"],
    oauthCapable: false,
    apiKeyCapable: true,
  },
  {
    id: "make",
    name: "Make",
    description: "Trigger Make scenarios from ZOLANZO webhooks and Public API reads.",
    category: "automation",
    version: "1.0.0",
    requiredScopes: ["webhooks.read", "webhooks.write", "analytics.read"],
    supportedWebhooks: [
      "report.generated",
      "forecast.generated",
      "trust.badge_awarded",
    ],
    supportedApiEndpoints: [
      "/api/v1/analytics/snapshots",
      "/api/v1/webhooks",
    ],
    configurationSchema: [
      {
        key: "scenarioHookUrl",
        label: "Make webhook URL",
        type: "url",
        required: true,
      },
    ],
    healthChecks: ["hook_reachable"],
    oauthCapable: false,
    apiKeyCapable: true,
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Self-hosted automation via Public API + webhook subscriptions.",
    category: "automation",
    version: "1.0.0",
    requiredScopes: ["webhooks.read", "webhooks.write", "automation.read"],
    supportedWebhooks: [
      "automation.rule.published",
      "automation.execution.completed",
      "assignment.completed",
    ],
    supportedApiEndpoints: [
      "/api/v1/automation/rules",
      "/api/v1/webhooks",
    ],
    configurationSchema: [
      {
        key: "webhookUrl",
        label: "n8n webhook URL",
        type: "url",
        required: true,
      },
      {
        key: "workflowId",
        label: "Workflow ID",
        type: "string",
        required: false,
      },
    ],
    healthChecks: ["hook_reachable"],
    oauthCapable: false,
    apiKeyCapable: true,
  },
];
