export interface MarketplaceTask {
  id: string;
  title: string;
  category: "AI" | "Social Media" | "Research" | "Writing" | "Customer Support" | "Data Entry" | "Virtual Assistant" | "Business";
  reward: string;
  rewardNumeric: number;
  estimatedTime: string;
  difficulty: "Easy" | "Medium" | "Advanced";
  availableSlots: number;
  totalSlots: number;
  slotStatus: "Open" | "Few Slots Left" | "Almost Full" | "Premium";
  location: "Remote (Nigeria)" | "Remote (Africa)" | "Lagos, Nigeria" | "Abuja, Nigeria";
  employerName: string;
  employerRating: number;
  employerVerified: boolean;
  featured?: boolean;
  recommended?: boolean;
  shortDescription: string;
  requirements: string[];
  postedTime: string;
}

export const MOCK_TASKS: MarketplaceTask[] = [
  {
    id: "task-101",
    title: "Yoruba & Igbo Speech Audio Transcription & Labeling",
    category: "AI",
    reward: "₦4,500",
    rewardNumeric: 4500,
    estimatedTime: "25 mins",
    difficulty: "Easy",
    availableSlots: 14,
    totalSlots: 100,
    slotStatus: "Open",
    location: "Remote (Nigeria)",
    employerName: "Kora AI Labs",
    employerRating: 4.9,
    employerVerified: true,
    featured: true,
    recommended: true,
    shortDescription: "Listen to 15 short audio clips in Yoruba or Igbo and verify text transcriptions for LLM model training.",
    requirements: ["Fluent in Yoruba or Igbo", "Quiet environment", "Headphones recommended"],
    postedTime: "10 mins ago",
  },
  {
    id: "task-102",
    title: "Fintech App UI Testing & User Experience Feedback",
    category: "Research",
    reward: "₦2,500",
    rewardNumeric: 2500,
    estimatedTime: "15 mins",
    difficulty: "Easy",
    availableSlots: 3,
    totalSlots: 50,
    slotStatus: "Few Slots Left",
    location: "Remote (Nigeria)",
    employerName: "Mono Technologies",
    employerRating: 4.8,
    employerVerified: true,
    featured: true,
    recommended: true,
    shortDescription: "Complete 3 test transfers on a sandbox banking app and answer 5 feedback survey questions.",
    requirements: ["Android or iOS Smartphone", "Active internet connection"],
    postedTime: "25 mins ago",
  },
  {
    id: "task-103",
    title: "E-Commerce Product Image Background Removal & Tagging",
    category: "AI",
    reward: "₦6,000",
    rewardNumeric: 6000,
    estimatedTime: "40 mins",
    difficulty: "Medium",
    availableSlots: 8,
    totalSlots: 20,
    slotStatus: "Open",
    location: "Remote (Africa)",
    employerName: "Jumia Digital Merchant",
    employerRating: 5.0,
    employerVerified: true,
    featured: true,
    recommended: true,
    shortDescription: "Clean product backgrounds using web AI tools and tag 25 fashion catalog items with category labels.",
    requirements: ["Laptop or tablet preferred", "Basic image editing familiarity"],
    postedTime: "1 hour ago",
  },
  {
    id: "task-104",
    title: "Instagram Product Video Engagement & Review",
    category: "Social Media",
    reward: "₦850",
    rewardNumeric: 850,
    estimatedTime: "5 mins",
    difficulty: "Easy",
    availableSlots: 180,
    totalSlots: 500,
    slotStatus: "Open",
    location: "Remote (Nigeria)",
    employerName: "BeautyBlend NG",
    employerRating: 4.7,
    employerVerified: true,
    recommended: true,
    shortDescription: "Watch brand demo reel, leave an authentic 2-sentence comment, and share to story.",
    requirements: ["Active Instagram account (over 30 days old)"],
    postedTime: "2 hours ago",
  },
  {
    id: "task-105",
    title: "Customer Support Live Chat Representative (Evening Shift)",
    category: "Customer Support",
    reward: "₦12,000",
    rewardNumeric: 12000,
    estimatedTime: "3 hrs",
    difficulty: "Advanced",
    availableSlots: 2,
    totalSlots: 5,
    slotStatus: "Few Slots Left",
    location: "Remote (Nigeria)",
    employerName: "Paystack Merchants",
    employerRating: 4.9,
    employerVerified: true,
    featured: true,
    shortDescription: "Handle inbound live chat inquiries for an online retail brand between 6 PM - 9 PM.",
    requirements: ["Fast typing speed (>45 WPM)", "Professional written communication"],
    postedTime: "30 mins ago",
  },
  {
    id: "task-106",
    title: "Real Estate Property Catalog Data Entry",
    category: "Data Entry",
    reward: "₦3,800",
    rewardNumeric: 3800,
    estimatedTime: "30 mins",
    difficulty: "Easy",
    availableSlots: 25,
    totalSlots: 100,
    slotStatus: "Open",
    location: "Lagos, Nigeria",
    employerName: "Haven Homes Ltd",
    employerRating: 4.6,
    employerVerified: true,
    shortDescription: "Copy property specs from PDF listings into standardized Google Sheets fields.",
    requirements: ["Spreadsheet skills (Google Sheets / Excel)"],
    postedTime: "3 hours ago",
  },
  {
    id: "task-107",
    title: "SaaS Blog Article Proofreading & SEO Keyword Check",
    category: "Writing",
    reward: "₦7,500",
    rewardNumeric: 7500,
    estimatedTime: "45 mins",
    difficulty: "Medium",
    availableSlots: 1,
    totalSlots: 3,
    slotStatus: "Almost Full",
    location: "Remote (Africa)",
    employerName: "GrowthPulse Media",
    employerRating: 4.9,
    employerVerified: true,
    shortDescription: "Review a 1,200-word tech blog post for grammar, tone consistency, and keyword placement.",
    requirements: ["Strong English grammar", "Basic SEO understanding"],
    postedTime: "15 mins ago",
  },
  {
    id: "task-108",
    title: "Executive Calendar Management & Meeting Scheduling",
    category: "Virtual Assistant",
    reward: "₦15,000",
    rewardNumeric: 15000,
    estimatedTime: "2 hrs",
    difficulty: "Advanced",
    availableSlots: 2,
    totalSlots: 4,
    slotStatus: "Premium",
    location: "Abuja, Nigeria",
    employerName: "Vanguard Ventures",
    employerRating: 5.0,
    employerVerified: true,
    featured: true,
    shortDescription: "Coordinate Google Calendar invites, send meeting reminders, and organize daily agendas for 2 executives.",
    requirements: ["Google Workspace proficiency", "High attention to detail"],
    postedTime: "4 hours ago",
  },
  {
    id: "task-109",
    title: "Market Research Survey: Gen-Z Mobile Shopping Habits",
    category: "Research",
    reward: "₦1,200",
    rewardNumeric: 1200,
    estimatedTime: "10 mins",
    difficulty: "Easy",
    availableSlots: 340,
    totalSlots: 1000,
    slotStatus: "Open",
    location: "Remote (Nigeria)",
    employerName: "Kantar Insights West Africa",
    employerRating: 4.8,
    employerVerified: true,
    recommended: true,
    shortDescription: "Complete a 12-question multiple-choice survey regarding online shopping frequency and payment preference.",
    requirements: ["Reside in Nigeria", "Aged 18-35"],
    postedTime: "5 hours ago",
  },
  {
    id: "task-110",
    title: "LinkedIn B2B Company Prospect Research",
    category: "Business",
    reward: "₦8,000",
    rewardNumeric: 8000,
    estimatedTime: "50 mins",
    difficulty: "Medium",
    availableSlots: 5,
    totalSlots: 15,
    slotStatus: "Open",
    location: "Remote (Nigeria)",
    employerName: "Terragon Group",
    employerRating: 4.7,
    employerVerified: true,
    shortDescription: "Find verified work emails and LinkedIn profiles for 20 Logistics Directors in West Africa.",
    requirements: ["LinkedIn account", "Email verification tool usage"],
    postedTime: "2 hours ago",
  },
  {
    id: "task-111",
    title: "Computer Vision Object Bounding Box Tagging",
    category: "AI",
    reward: "₦5,200",
    rewardNumeric: 5200,
    estimatedTime: "35 mins",
    difficulty: "Easy",
    availableSlots: 60,
    totalSlots: 200,
    slotStatus: "Open",
    location: "Remote (Africa)",
    employerName: "Zindi AI Community",
    employerRating: 4.9,
    employerVerified: true,
    shortDescription: "Draw bounding boxes around vehicles and pedestrians in 40 traffic camera images.",
    requirements: ["Desktop or Laptop", "Mouse control precision"],
    postedTime: "6 hours ago",
  },
  {
    id: "task-112",
    title: "X (Twitter) Product Announcement Re-Share & Quote",
    category: "Social Media",
    reward: "₦600",
    rewardNumeric: 600,
    estimatedTime: "3 mins",
    difficulty: "Easy",
    availableSlots: 210,
    totalSlots: 600,
    slotStatus: "Open",
    location: "Remote (Nigeria)",
    employerName: "PiggyVest Brand Team",
    employerRating: 4.9,
    employerVerified: true,
    shortDescription: "Quote tweet launch announcement with custom hashtag and 1 sentence of positive feedback.",
    requirements: ["Active Twitter/X account with >100 followers"],
    postedTime: "1 hour ago",
  },
  {
    id: "task-113",
    title: "Short Product Unboxing Video Creation (15 Secs)",
    category: "Writing",
    reward: "₦10,000",
    rewardNumeric: 10000,
    estimatedTime: "20 mins",
    difficulty: "Medium",
    availableSlots: 4,
    totalSlots: 10,
    slotStatus: "Few Slots Left",
    location: "Lagos, Nigeria",
    employerName: "Slot Systems NG",
    employerRating: 4.8,
    employerVerified: true,
    featured: true,
    shortDescription: "Record a crisp 15-second vertical unboxing clip of phone accessory package and submit raw video.",
    requirements: ["Smartphone with HD camera", "Good lighting"],
    postedTime: "3 hours ago",
  },
  {
    id: "task-114",
    title: "Local Business Google Maps Address & Phone Audit",
    category: "Data Entry",
    reward: "₦3,200",
    rewardNumeric: 3200,
    estimatedTime: "25 mins",
    difficulty: "Easy",
    availableSlots: 18,
    totalSlots: 40,
    slotStatus: "Open",
    location: "Abuja, Nigeria",
    employerName: "YellowPages Digital",
    employerRating: 4.5,
    employerVerified: true,
    shortDescription: "Call 10 listed business numbers in Ikeja/Abuja to verify store opening hours.",
    requirements: ["Mobile call line", "Quiet phone call setting"],
    postedTime: "4 hours ago",
  },
  {
    id: "task-115",
    title: "French to English Document Translation Verification",
    category: "Writing",
    reward: "₦9,000",
    rewardNumeric: 9000,
    estimatedTime: "45 mins",
    difficulty: "Advanced",
    availableSlots: 2,
    totalSlots: 5,
    slotStatus: "Few Slots Left",
    location: "Remote (Africa)",
    employerName: "Ecobank Regional HQ",
    employerRating: 5.0,
    employerVerified: true,
    shortDescription: "Compare 4 pages of French corporate press releases against English translations for accuracy.",
    requirements: ["Bilingual French & English fluency"],
    postedTime: "5 hours ago",
  },
];
