/**
 * Feature module registry — architecture index.
 */

export const FEATURE_MODULES = [
  "authentication",
  "users",
  "organizations",
  "teams",
  "workers",
  "clients",
  /** @deprecated Use clients */
  "advertisers",
  "campaigns",
  "task-templates",
  "tasks",
  "task-marketplace",
  "applications",
  "assignments",
  "submissions",
  "verification",
  "ledger",
  "wallet",
  "payments",
  "escrow",
  "withdrawals",
  "settlements",
  "rewards",
  "referrals",
  "notifications",
  "messaging",
  "ai-jobs",
  "ai-datasets",
  "ai-labeling",
  "voice-collection",
  "image-annotation",
  "video-annotation",
  "translation",
  "research",
  "testing",
  "qa",
  "bug-reports",
  "moderation",
  "reports",
  "trust-and-safety",
  "kyc",
  "disputes",
  "admin",
  "ai-platform",
  "analytics",
  "api",
  "developer-portal",
  "documentation",
  "support",
  "settings",
] as const;

export type FeatureModuleId = (typeof FEATURE_MODULES)[number];
